apiVersion: argoproj.io/v1alpha1
kind: Secret
metadata:
  name: private-repo-creds
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds
data:
  sshPrivateKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCzDfNogvY/E6Kqm1bS5PMmRrfb1Jg+meSq398iVnX/Wa8F/E8e1Egtdf/0ypYK41LNkqJ5reccc9uSMH8hUM2toSX7MMcVtEKq8PqMU9pgVpQI7gD60iATElNJWqcU9yPb9631oLSOUfknx2Oy2gZ70bSSkPZg3lb8vlqQsMMWTPMgpHzKCOl8lFOyRL3WE1rW8pUpGfKU553Mhb+OZ1JPbZ2udLfv9GkJ2u9fWkb7eDzDyMMtbg2jOqAJiFcJdAxwbsUKfcYlgYLos9ZtdaLVjIotWZI9+rCm7rK4H5an+uFFBvS+7nA1ZdMM4Xw/B6FO87Xrn8db+fj5u4o2tqHW0Es2bUvAFBAamxe46YfVQHQl1G7UaZTuvSBh4YOUShhglDwgcOlJ44pqpmqg6r1WLo9fwl1C0JdMHhoEI5aIkYxxuQtj37u0tfgQpmYk5lhRt+Qo43URnFAYfTuJzqrHAvEslEGLa4JUYgYebpYV5836hKuUM4sbkC09deU7g/M= corp\sk19272@ojas-dl487
